name: Deploy

permissions:
  contents: write
  packages: write

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  get-version:
    if: (github.ref == 'refs/heads/master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: get-version
        run: |
          VERSION=$(cat version)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    outputs:
      version: ${{ steps.get-version.outputs.version }}

  build-and-push-image:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ needs.get-version.outputs.version }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.Production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    outputs:
      version: ${{ needs.get-version.outputs.version }}
  
  update-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Update the ec2 instance
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          ANTHEM_PAT: ${{ secrets.ANTHEM_PAT }}
          IMAGE_NAME: "ghcr.io/anthem-org/anthemapi:${{ needs.build-and-push-image.outputs.version }}"
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          echo "Updating to image name: ${IMAGE_NAME}"

          ssh -v -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
            echo "Logging into GHCR..."
            echo $ANTHEM_PAT | docker login ghcr.io -u anthem-org --password-stdin
            echo "Pulling Docker image..."
            docker pull ${IMAGE_NAME}
            echo "Stopping the Anthem API container..."
            docker stop anthemapi
            echo "Pruning all stopped containers..."
            docker container prune -f
            echo "Running the new image..."
            docker run -d -p 8080:8080 --name anthemapi ${IMAGE_NAME}
            echo "Deleting all Docker images not in use..."
            docker image prune -a -f
            exit
          EOF
      - name: Cleanup
        run: rm -f private_key
    outputs:
      version: ${{ needs.build-and-push-image.outputs.version }}
    
  create-tag-and-release:
    needs: update-ec2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push tag
        env:
          VERSION: ${{ needs.update-ec2.outputs.version }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.update-ec2.outputs.version }}
          release_name: Release ${{ needs.update-ec2.outputs.version }}
          draft: false
          prerelease: false
